# coding: utf-8

"""
    OWASP Dependency-Track

    REST API of OWASP Dependency-Track  # noqa: E501

    OpenAPI spec version: 4.13.4
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.user_api import UserApi  # noqa: E501
from swagger_client.rest import ApiException


class TestUserApi(unittest.TestCase):
    """UserApi unit test stubs"""

    def setUp(self):
        self.api = UserApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_add_team_to_user(self):
        """Test case for add_team_to_user

        Adds the username to the specified team.  # noqa: E501
        """
        pass

    def test_create_ldap_user(self):
        """Test case for create_ldap_user

        Creates a new user that references an existing LDAP object.  # noqa: E501
        """
        pass

    def test_create_managed_user(self):
        """Test case for create_managed_user

        Creates a new user.  # noqa: E501
        """
        pass

    def test_create_oidc_user(self):
        """Test case for create_oidc_user

        Creates a new user that references an existing OpenID Connect user.  # noqa: E501
        """
        pass

    def test_delete_ldap_user(self):
        """Test case for delete_ldap_user

        Deletes a user.  # noqa: E501
        """
        pass

    def test_delete_managed_user(self):
        """Test case for delete_managed_user

        Deletes a user.  # noqa: E501
        """
        pass

    def test_delete_oidc_user(self):
        """Test case for delete_oidc_user

        Deletes an OpenID Connect user.  # noqa: E501
        """
        pass

    def test_force_change_password(self):
        """Test case for force_change_password

        Asserts login credentials and upon successful authentication, verifies passwords match and changes users password  # noqa: E501
        """
        pass

    def test_get_ldap_users(self):
        """Test case for get_ldap_users

        Returns a list of all LDAP users  # noqa: E501
        """
        pass

    def test_get_managed_users(self):
        """Test case for get_managed_users

        Returns a list of all managed users  # noqa: E501
        """
        pass

    def test_get_oidc_users(self):
        """Test case for get_oidc_users

        Returns a list of all OIDC users  # noqa: E501
        """
        pass

    def test_get_self1(self):
        """Test case for get_self1

        Returns information about the current logged in user.  # noqa: E501
        """
        pass

    def test_remove_team_from_user(self):
        """Test case for remove_team_from_user

        Removes the username from the specified team.  # noqa: E501
        """
        pass

    def test_update_managed_user(self):
        """Test case for update_managed_user

        Updates a managed user.  # noqa: E501
        """
        pass

    def test_update_self(self):
        """Test case for update_self

        Updates information about the current logged in user.  # noqa: E501
        """
        pass

    def test_validate_credentials(self):
        """Test case for validate_credentials

        Assert login credentials  # noqa: E501
        """
        pass

    def test_validate_oidc_access_token(self):
        """Test case for validate_oidc_access_token

        Login with OpenID Connect  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
