# coding: utf-8

"""
    OWASP Dependency-Track

    REST API of OWASP Dependency-Track  # noqa: E501

    OpenAPI spec version: 4.13.4
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.project_property_api import ProjectPropertyApi  # noqa: E501
from swagger_client.rest import ApiException


class TestProjectPropertyApi(unittest.TestCase):
    """ProjectPropertyApi unit test stubs"""

    def setUp(self):
        self.api = ProjectPropertyApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_property1(self):
        """Test case for create_property1

        Creates a new project property  # noqa: E501
        """
        pass

    def test_delete_property1(self):
        """Test case for delete_property1

        Deletes a config property  # noqa: E501
        """
        pass

    def test_get_properties1(self):
        """Test case for get_properties1

        Returns a list of all ProjectProperties for the specified project  # noqa: E501
        """
        pass

    def test_update_property(self):
        """Test case for update_property

        Updates a project property  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
