# coding: utf-8

"""
    OWASP Dependency-Track

    REST API of OWASP Dependency-Track  # noqa: E501

    OpenAPI spec version: 4.13.4
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.project_metrics import ProjectMetrics  # noqa: E501
from swagger_client.rest import ApiException


class TestProjectMetrics(unittest.TestCase):
    """ProjectMetrics unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testProjectMetrics(self):
        """Test ProjectMetrics"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.project_metrics.ProjectMetrics()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
