# coding: utf-8

"""
    OWASP Dependency-Track

    REST API of OWASP Dependency-Track  # noqa: E501

    OpenAPI spec version: 4.13.4
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.component_property_api import ComponentPropertyApi  # noqa: E501
from swagger_client.rest import ApiException


class TestComponentPropertyApi(unittest.TestCase):
    """ComponentPropertyApi unit test stubs"""

    def setUp(self):
        self.api = ComponentPropertyApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_property(self):
        """Test case for create_property

        Creates a new component property  # noqa: E501
        """
        pass

    def test_delete_property(self):
        """Test case for delete_property

        Deletes a config property  # noqa: E501
        """
        pass

    def test_get_properties(self):
        """Test case for get_properties

        Returns a list of all properties for the specified component  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
