# coding: utf-8

"""
    OWASP Dependency-Track

    REST API of OWASP Dependency-Track  # noqa: E501

    OpenAPI spec version: 4.13.4
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.policy_condition_api import PolicyConditionApi  # noqa: E501
from swagger_client.rest import ApiException


class TestPolicyConditionApi(unittest.TestCase):
    """PolicyConditionApi unit test stubs"""

    def setUp(self):
        self.api = PolicyConditionApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_policy_condition(self):
        """Test case for create_policy_condition

        Creates a new policy condition  # noqa: E501
        """
        pass

    def test_delete_policy_condition(self):
        """Test case for delete_policy_condition

        Deletes a policy condition  # noqa: E501
        """
        pass

    def test_update_policy_condition(self):
        """Test case for update_policy_condition

        Updates a policy condition  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
