# coding: utf-8

"""
    OWASP Dependency-Track

    REST API of OWASP Dependency-Track  # noqa: E501

    OpenAPI spec version: 4.13.4
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.team_api import TeamApi  # noqa: E501
from swagger_client.rest import ApiException


class TestTeamApi(unittest.TestCase):
    """TeamApi unit test stubs"""

    def setUp(self):
        self.api = TeamApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_available_teams(self):
        """Test case for available_teams

        Returns a list of Teams that are visible  # noqa: E501
        """
        pass

    def test_create_team(self):
        """Test case for create_team

        Creates a new team  # noqa: E501
        """
        pass

    def test_delete_api_key(self):
        """Test case for delete_api_key

        Deletes the specified API key  # noqa: E501
        """
        pass

    def test_delete_team(self):
        """Test case for delete_team

        Deletes a team  # noqa: E501
        """
        pass

    def test_generate_api_key(self):
        """Test case for generate_api_key

        Generates an API key and returns its value  # noqa: E501
        """
        pass

    def test_get_self(self):
        """Test case for get_self

        Returns information about the current team.  # noqa: E501
        """
        pass

    def test_get_team(self):
        """Test case for get_team

        Returns a specific team  # noqa: E501
        """
        pass

    def test_get_teams(self):
        """Test case for get_teams

        Returns a list of all teams  # noqa: E501
        """
        pass

    def test_regenerate_api_key(self):
        """Test case for regenerate_api_key

        Regenerates an API key by removing the specified key, generating a new one and returning its value  # noqa: E501
        """
        pass

    def test_update_api_key_comment(self):
        """Test case for update_api_key_comment

        Updates an API key's comment  # noqa: E501
        """
        pass

    def test_update_team(self):
        """Test case for update_team

        Updates a team's fields  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
