# coding: utf-8

"""
    OWASP Dependency-Track

    REST API of OWASP Dependency-Track  # noqa: E501

    OpenAPI spec version: 4.13.4
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.cwe_api import CweApi  # noqa: E501
from swagger_client.rest import ApiException


class TestCweApi(unittest.TestCase):
    """CweApi unit test stubs"""

    def setUp(self):
        self.api = CweApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_cwe(self):
        """Test case for get_cwe

        Returns a specific CWE  # noqa: E501
        """
        pass

    def test_get_cwes(self):
        """Test case for get_cwes

        Returns a list of all CWEs  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
