# coding: utf-8

"""
    OWASP Dependency-Track

    REST API of OWASP Dependency-Track  # noqa: E501

    OpenAPI spec version: 4.13.4
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.notification_api import NotificationApi  # noqa: E501
from swagger_client.rest import ApiException


class TestNotificationApi(unittest.TestCase):
    """NotificationApi unit test stubs"""

    def setUp(self):
        self.api = NotificationApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_add_project_to_rule(self):
        """Test case for add_project_to_rule

        Adds a project to a notification rule  # noqa: E501
        """
        pass

    def test_add_team_to_rule(self):
        """Test case for add_team_to_rule

        Adds a team to a notification rule  # noqa: E501
        """
        pass

    def test_create_notification_publisher(self):
        """Test case for create_notification_publisher

        Creates a new notification publisher  # noqa: E501
        """
        pass

    def test_create_notification_rule(self):
        """Test case for create_notification_rule

        Creates a new notification rule  # noqa: E501
        """
        pass

    def test_create_scheduled_notification_rule(self):
        """Test case for create_scheduled_notification_rule

        Creates a new scheduled notification rule  # noqa: E501
        """
        pass

    def test_delete_notification_publisher(self):
        """Test case for delete_notification_publisher

        Deletes a notification publisher and all related notification rules  # noqa: E501
        """
        pass

    def test_delete_notification_rule(self):
        """Test case for delete_notification_rule

        Deletes a notification rule  # noqa: E501
        """
        pass

    def test_get_all_notification_publishers(self):
        """Test case for get_all_notification_publishers

        Returns a list of all notification publishers  # noqa: E501
        """
        pass

    def test_get_all_notification_rules(self):
        """Test case for get_all_notification_rules

        Returns a list of all notification rules  # noqa: E501
        """
        pass

    def test_remove_project_from_rule(self):
        """Test case for remove_project_from_rule

        Removes a project from a notification rule  # noqa: E501
        """
        pass

    def test_remove_team_from_rule(self):
        """Test case for remove_team_from_rule

        Removes a team from a notification rule  # noqa: E501
        """
        pass

    def test_restore_default_templates(self):
        """Test case for restore_default_templates

        Restore the default notification publisher templates using the ones in the solution classpath  # noqa: E501
        """
        pass

    def test_test_notification_rule(self):
        """Test case for test_notification_rule

        Dispatches a rule notification test  # noqa: E501
        """
        pass

    def test_test_smtp_publisher_config(self):
        """Test case for test_smtp_publisher_config

        Dispatches a SMTP notification test  # noqa: E501
        """
        pass

    def test_update_notification_publisher(self):
        """Test case for update_notification_publisher

        Updates a notification publisher  # noqa: E501
        """
        pass

    def test_update_notification_rule(self):
        """Test case for update_notification_rule

        Updates a notification rule  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
