# coding: utf-8

"""
    OWASP Dependency-Track

    REST API of OWASP Dependency-Track  # noqa: E501

    OpenAPI spec version: 4.13.4
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.license_api import LicenseApi  # noqa: E501
from swagger_client.rest import ApiException


class TestLicenseApi(unittest.TestCase):
    """LicenseApi unit test stubs"""

    def setUp(self):
        self.api = LicenseApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_license(self):
        """Test case for create_license

        Creates a new custom license  # noqa: E501
        """
        pass

    def test_delete_license(self):
        """Test case for delete_license

        Deletes a custom license  # noqa: E501
        """
        pass

    def test_get_license(self):
        """Test case for get_license

        Returns a specific license  # noqa: E501
        """
        pass

    def test_get_license_listing(self):
        """Test case for get_license_listing

        Returns a concise listing of all licenses  # noqa: E501
        """
        pass

    def test_get_licenses(self):
        """Test case for get_licenses

        Returns a list of all licenses with complete metadata for each license  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
