# coding: utf-8

"""
    OWASP Dependency-Track

    REST API of OWASP Dependency-Track  # noqa: E501

    OpenAPI spec version: 4.13.4
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.dependency_graph_api import DependencyGraphApi  # noqa: E501
from swagger_client.rest import ApiException


class TestDependencyGraphApi(unittest.TestCase):
    """DependencyGraphApi unit test stubs"""

    def setUp(self):
        self.api = DependencyGraphApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_components_and_services_by_component_uuid(self):
        """Test case for get_components_and_services_by_component_uuid

        Returns a list of specific components and services from component UUID  # noqa: E501
        """
        pass

    def test_get_components_and_services_by_project_uuid(self):
        """Test case for get_components_and_services_by_project_uuid

        Returns a list of specific components and services from project UUID  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
