# coding: utf-8

"""
    OWASP Dependency-Track

    REST API of OWASP Dependency-Track  # noqa: E501

    OpenAPI spec version: 4.13.4
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.external_reference import ExternalReference  # noqa: E501
from swagger_client.rest import ApiException


class TestExternalReference(unittest.TestCase):
    """ExternalReference unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testExternalReference(self):
        """Test ExternalReference"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.external_reference.ExternalReference()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
