# coding: utf-8

"""
    OWASP Dependency-Track

    REST API of OWASP Dependency-Track  # noqa: E501

    OpenAPI spec version: 4.13.4
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.badge_api import BadgeApi  # noqa: E501
from swagger_client.rest import ApiException


class TestBadgeApi(unittest.TestCase):
    """BadgeApi unit test stubs"""

    def setUp(self):
        self.api = BadgeApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_project_policy_violations_badge(self):
        """Test case for get_project_policy_violations_badge

        Returns a policy violations badge for a specific project  # noqa: E501
        """
        pass

    def test_get_project_policy_violations_badge1(self):
        """Test case for get_project_policy_violations_badge1

        Returns a policy violations badge for a specific project  # noqa: E501
        """
        pass

    def test_get_project_vulnerabilities_badge(self):
        """Test case for get_project_vulnerabilities_badge

        Returns current metrics for a specific project  # noqa: E501
        """
        pass

    def test_get_project_vulnerabilities_badge1(self):
        """Test case for get_project_vulnerabilities_badge1

        Returns current metrics for a specific project  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
