# coding: utf-8

"""
    OWASP Dependency-Track

    REST API of OWASP Dependency-Track  # noqa: E501

    OpenAPI spec version: 4.13.4
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.visible_teams import VisibleTeams  # noqa: E501
from swagger_client.rest import ApiException


class TestVisibleTeams(unittest.TestCase):
    """VisibleTeams unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testVisibleTeams(self):
        """Test VisibleTeams"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.visible_teams.VisibleTeams()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
