# coding: utf-8

"""
    OWASP Dependency-Track

    REST API of OWASP Dependency-Track  # noqa: E501

    OpenAPI spec version: 4.13.4
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class Analysis(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'analysis_state': 'str',
        'analysis_justification': 'str',
        'analysis_response': 'str',
        'analysis_details': 'str',
        'analysis_comments': 'list[AnalysisComment]',
        'is_suppressed': 'bool'
    }

    attribute_map = {
        'analysis_state': 'analysisState',
        'analysis_justification': 'analysisJustification',
        'analysis_response': 'analysisResponse',
        'analysis_details': 'analysisDetails',
        'analysis_comments': 'analysisComments',
        'is_suppressed': 'isSuppressed'
    }

    def __init__(self, analysis_state=None, analysis_justification=None, analysis_response=None, analysis_details=None, analysis_comments=None, is_suppressed=None):  # noqa: E501
        """Analysis - a model defined in Swagger"""  # noqa: E501
        self._analysis_state = None
        self._analysis_justification = None
        self._analysis_response = None
        self._analysis_details = None
        self._analysis_comments = None
        self._is_suppressed = None
        self.discriminator = None
        self.analysis_state = analysis_state
        self.analysis_justification = analysis_justification
        self.analysis_response = analysis_response
        self.analysis_details = analysis_details
        if analysis_comments is not None:
            self.analysis_comments = analysis_comments
        if is_suppressed is not None:
            self.is_suppressed = is_suppressed

    @property
    def analysis_state(self):
        """Gets the analysis_state of this Analysis.  # noqa: E501


        :return: The analysis_state of this Analysis.  # noqa: E501
        :rtype: str
        """
        return self._analysis_state

    @analysis_state.setter
    def analysis_state(self, analysis_state):
        """Sets the analysis_state of this Analysis.


        :param analysis_state: The analysis_state of this Analysis.  # noqa: E501
        :type: str
        """
        if analysis_state is None:
            raise ValueError("Invalid value for `analysis_state`, must not be `None`")  # noqa: E501
        allowed_values = ["EXPLOITABLE", "IN_TRIAGE", "FALSE_POSITIVE", "NOT_AFFECTED", "RESOLVED", "NOT_SET"]  # noqa: E501
        if analysis_state not in allowed_values:
            raise ValueError(
                "Invalid value for `analysis_state` ({0}), must be one of {1}"  # noqa: E501
                .format(analysis_state, allowed_values)
            )

        self._analysis_state = analysis_state

    @property
    def analysis_justification(self):
        """Gets the analysis_justification of this Analysis.  # noqa: E501


        :return: The analysis_justification of this Analysis.  # noqa: E501
        :rtype: str
        """
        return self._analysis_justification

    @analysis_justification.setter
    def analysis_justification(self, analysis_justification):
        """Sets the analysis_justification of this Analysis.


        :param analysis_justification: The analysis_justification of this Analysis.  # noqa: E501
        :type: str
        """
        if analysis_justification is None:
            raise ValueError("Invalid value for `analysis_justification`, must not be `None`")  # noqa: E501
        allowed_values = ["CODE_NOT_PRESENT", "CODE_NOT_REACHABLE", "REQUIRES_CONFIGURATION", "REQUIRES_DEPENDENCY", "REQUIRES_ENVIRONMENT", "PROTECTED_BY_COMPILER", "PROTECTED_AT_RUNTIME", "PROTECTED_AT_PERIMETER", "PROTECTED_BY_MITIGATING_CONTROL", "NOT_SET"]  # noqa: E501
        if analysis_justification not in allowed_values:
            raise ValueError(
                "Invalid value for `analysis_justification` ({0}), must be one of {1}"  # noqa: E501
                .format(analysis_justification, allowed_values)
            )

        self._analysis_justification = analysis_justification

    @property
    def analysis_response(self):
        """Gets the analysis_response of this Analysis.  # noqa: E501


        :return: The analysis_response of this Analysis.  # noqa: E501
        :rtype: str
        """
        return self._analysis_response

    @analysis_response.setter
    def analysis_response(self, analysis_response):
        """Sets the analysis_response of this Analysis.


        :param analysis_response: The analysis_response of this Analysis.  # noqa: E501
        :type: str
        """
        if analysis_response is None:
            raise ValueError("Invalid value for `analysis_response`, must not be `None`")  # noqa: E501
        allowed_values = ["CAN_NOT_FIX", "WILL_NOT_FIX", "UPDATE", "ROLLBACK", "WORKAROUND_AVAILABLE", "NOT_SET"]  # noqa: E501
        if analysis_response not in allowed_values:
            raise ValueError(
                "Invalid value for `analysis_response` ({0}), must be one of {1}"  # noqa: E501
                .format(analysis_response, allowed_values)
            )

        self._analysis_response = analysis_response

    @property
    def analysis_details(self):
        """Gets the analysis_details of this Analysis.  # noqa: E501


        :return: The analysis_details of this Analysis.  # noqa: E501
        :rtype: str
        """
        return self._analysis_details

    @analysis_details.setter
    def analysis_details(self, analysis_details):
        """Sets the analysis_details of this Analysis.


        :param analysis_details: The analysis_details of this Analysis.  # noqa: E501
        :type: str
        """
        if analysis_details is None:
            raise ValueError("Invalid value for `analysis_details`, must not be `None`")  # noqa: E501

        self._analysis_details = analysis_details

    @property
    def analysis_comments(self):
        """Gets the analysis_comments of this Analysis.  # noqa: E501


        :return: The analysis_comments of this Analysis.  # noqa: E501
        :rtype: list[AnalysisComment]
        """
        return self._analysis_comments

    @analysis_comments.setter
    def analysis_comments(self, analysis_comments):
        """Sets the analysis_comments of this Analysis.


        :param analysis_comments: The analysis_comments of this Analysis.  # noqa: E501
        :type: list[AnalysisComment]
        """

        self._analysis_comments = analysis_comments

    @property
    def is_suppressed(self):
        """Gets the is_suppressed of this Analysis.  # noqa: E501


        :return: The is_suppressed of this Analysis.  # noqa: E501
        :rtype: bool
        """
        return self._is_suppressed

    @is_suppressed.setter
    def is_suppressed(self, is_suppressed):
        """Sets the is_suppressed of this Analysis.


        :param is_suppressed: The is_suppressed of this Analysis.  # noqa: E501
        :type: bool
        """

        self._is_suppressed = is_suppressed

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Analysis, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Analysis):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
