# coding: utf-8

"""
    OWASP Dependency-Track

    REST API of OWASP Dependency-Track  # noqa: E501

    OpenAPI spec version: 4.13.4
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class DependencyGraphResponse(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'uuid': 'str',
        'name': 'str',
        'version': 'str',
        'purl': 'str',
        'direct_dependencies': 'str',
        'latest_version': 'str'
    }

    attribute_map = {
        'uuid': 'uuid',
        'name': 'name',
        'version': 'version',
        'purl': 'purl',
        'direct_dependencies': 'directDependencies',
        'latest_version': 'latestVersion'
    }

    def __init__(self, uuid=None, name=None, version=None, purl=None, direct_dependencies=None, latest_version=None):  # noqa: E501
        """DependencyGraphResponse - a model defined in Swagger"""  # noqa: E501
        self._uuid = None
        self._name = None
        self._version = None
        self._purl = None
        self._direct_dependencies = None
        self._latest_version = None
        self.discriminator = None
        if uuid is not None:
            self.uuid = uuid
        if name is not None:
            self.name = name
        if version is not None:
            self.version = version
        if purl is not None:
            self.purl = purl
        if direct_dependencies is not None:
            self.direct_dependencies = direct_dependencies
        if latest_version is not None:
            self.latest_version = latest_version

    @property
    def uuid(self):
        """Gets the uuid of this DependencyGraphResponse.  # noqa: E501


        :return: The uuid of this DependencyGraphResponse.  # noqa: E501
        :rtype: str
        """
        return self._uuid

    @uuid.setter
    def uuid(self, uuid):
        """Sets the uuid of this DependencyGraphResponse.


        :param uuid: The uuid of this DependencyGraphResponse.  # noqa: E501
        :type: str
        """

        self._uuid = uuid

    @property
    def name(self):
        """Gets the name of this DependencyGraphResponse.  # noqa: E501


        :return: The name of this DependencyGraphResponse.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this DependencyGraphResponse.


        :param name: The name of this DependencyGraphResponse.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def version(self):
        """Gets the version of this DependencyGraphResponse.  # noqa: E501


        :return: The version of this DependencyGraphResponse.  # noqa: E501
        :rtype: str
        """
        return self._version

    @version.setter
    def version(self, version):
        """Sets the version of this DependencyGraphResponse.


        :param version: The version of this DependencyGraphResponse.  # noqa: E501
        :type: str
        """

        self._version = version

    @property
    def purl(self):
        """Gets the purl of this DependencyGraphResponse.  # noqa: E501


        :return: The purl of this DependencyGraphResponse.  # noqa: E501
        :rtype: str
        """
        return self._purl

    @purl.setter
    def purl(self, purl):
        """Sets the purl of this DependencyGraphResponse.


        :param purl: The purl of this DependencyGraphResponse.  # noqa: E501
        :type: str
        """

        self._purl = purl

    @property
    def direct_dependencies(self):
        """Gets the direct_dependencies of this DependencyGraphResponse.  # noqa: E501


        :return: The direct_dependencies of this DependencyGraphResponse.  # noqa: E501
        :rtype: str
        """
        return self._direct_dependencies

    @direct_dependencies.setter
    def direct_dependencies(self, direct_dependencies):
        """Sets the direct_dependencies of this DependencyGraphResponse.


        :param direct_dependencies: The direct_dependencies of this DependencyGraphResponse.  # noqa: E501
        :type: str
        """

        self._direct_dependencies = direct_dependencies

    @property
    def latest_version(self):
        """Gets the latest_version of this DependencyGraphResponse.  # noqa: E501


        :return: The latest_version of this DependencyGraphResponse.  # noqa: E501
        :rtype: str
        """
        return self._latest_version

    @latest_version.setter
    def latest_version(self, latest_version):
        """Sets the latest_version of this DependencyGraphResponse.


        :param latest_version: The latest_version of this DependencyGraphResponse.  # noqa: E501
        :type: str
        """

        self._latest_version = latest_version

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(DependencyGraphResponse, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, DependencyGraphResponse):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
