# coding: utf-8

"""
    OWASP Dependency-Track

    REST API of OWASP Dependency-Track  # noqa: E501

    OpenAPI spec version: 4.13.4
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class OrganizationalEntity(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'name': 'str',
        'urls': 'list[str]',
        'contacts': 'list[OrganizationalContact]'
    }

    attribute_map = {
        'name': 'name',
        'urls': 'urls',
        'contacts': 'contacts'
    }

    def __init__(self, name=None, urls=None, contacts=None):  # noqa: E501
        """OrganizationalEntity - a model defined in Swagger"""  # noqa: E501
        self._name = None
        self._urls = None
        self._contacts = None
        self.discriminator = None
        if name is not None:
            self.name = name
        if urls is not None:
            self.urls = urls
        if contacts is not None:
            self.contacts = contacts

    @property
    def name(self):
        """Gets the name of this OrganizationalEntity.  # noqa: E501


        :return: The name of this OrganizationalEntity.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this OrganizationalEntity.


        :param name: The name of this OrganizationalEntity.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def urls(self):
        """Gets the urls of this OrganizationalEntity.  # noqa: E501


        :return: The urls of this OrganizationalEntity.  # noqa: E501
        :rtype: list[str]
        """
        return self._urls

    @urls.setter
    def urls(self, urls):
        """Sets the urls of this OrganizationalEntity.


        :param urls: The urls of this OrganizationalEntity.  # noqa: E501
        :type: list[str]
        """

        self._urls = urls

    @property
    def contacts(self):
        """Gets the contacts of this OrganizationalEntity.  # noqa: E501


        :return: The contacts of this OrganizationalEntity.  # noqa: E501
        :rtype: list[OrganizationalContact]
        """
        return self._contacts

    @contacts.setter
    def contacts(self, contacts):
        """Sets the contacts of this OrganizationalEntity.


        :param contacts: The contacts of this OrganizationalEntity.  # noqa: E501
        :type: list[OrganizationalContact]
        """

        self._contacts = contacts

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(OrganizationalEntity, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, OrganizationalEntity):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
