# coding: utf-8

"""
    OWASP Dependency-Track

    REST API of OWASP Dependency-Track  # noqa: E501

    OpenAPI spec version: 4.13.4
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class UserPrincipal(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'int',
        'name': 'str',
        'permissions': 'list[Permission]',
        'username': 'str',
        'teams': 'list[Team]',
        'email': 'str'
    }

    attribute_map = {
        'id': 'id',
        'name': 'name',
        'permissions': 'permissions',
        'username': 'username',
        'teams': 'teams',
        'email': 'email'
    }

    def __init__(self, id=None, name=None, permissions=None, username=None, teams=None, email=None):  # noqa: E501
        """UserPrincipal - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._name = None
        self._permissions = None
        self._username = None
        self._teams = None
        self._email = None
        self.discriminator = None
        if id is not None:
            self.id = id
        if name is not None:
            self.name = name
        if permissions is not None:
            self.permissions = permissions
        if username is not None:
            self.username = username
        if teams is not None:
            self.teams = teams
        if email is not None:
            self.email = email

    @property
    def id(self):
        """Gets the id of this UserPrincipal.  # noqa: E501


        :return: The id of this UserPrincipal.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this UserPrincipal.


        :param id: The id of this UserPrincipal.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def name(self):
        """Gets the name of this UserPrincipal.  # noqa: E501


        :return: The name of this UserPrincipal.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this UserPrincipal.


        :param name: The name of this UserPrincipal.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def permissions(self):
        """Gets the permissions of this UserPrincipal.  # noqa: E501


        :return: The permissions of this UserPrincipal.  # noqa: E501
        :rtype: list[Permission]
        """
        return self._permissions

    @permissions.setter
    def permissions(self, permissions):
        """Sets the permissions of this UserPrincipal.


        :param permissions: The permissions of this UserPrincipal.  # noqa: E501
        :type: list[Permission]
        """

        self._permissions = permissions

    @property
    def username(self):
        """Gets the username of this UserPrincipal.  # noqa: E501


        :return: The username of this UserPrincipal.  # noqa: E501
        :rtype: str
        """
        return self._username

    @username.setter
    def username(self, username):
        """Sets the username of this UserPrincipal.


        :param username: The username of this UserPrincipal.  # noqa: E501
        :type: str
        """

        self._username = username

    @property
    def teams(self):
        """Gets the teams of this UserPrincipal.  # noqa: E501


        :return: The teams of this UserPrincipal.  # noqa: E501
        :rtype: list[Team]
        """
        return self._teams

    @teams.setter
    def teams(self, teams):
        """Sets the teams of this UserPrincipal.


        :param teams: The teams of this UserPrincipal.  # noqa: E501
        :type: list[Team]
        """

        self._teams = teams

    @property
    def email(self):
        """Gets the email of this UserPrincipal.  # noqa: E501


        :return: The email of this UserPrincipal.  # noqa: E501
        :rtype: str
        """
        return self._email

    @email.setter
    def email(self, email):
        """Sets the email of this UserPrincipal.


        :param email: The email of this UserPrincipal.  # noqa: E501
        :type: str
        """

        self._email = email

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(UserPrincipal, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, UserPrincipal):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
