# coding: utf-8

"""
    OWASP Dependency-Track

    REST API of OWASP Dependency-Track  # noqa: E501

    OpenAPI spec version: 4.13.4
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class V1VexBody(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'project': 'str',
        'project_name': 'str',
        'project_version': 'str',
        'vex': 'str'
    }

    attribute_map = {
        'project': 'project',
        'project_name': 'projectName',
        'project_version': 'projectVersion',
        'vex': 'vex'
    }

    def __init__(self, project=None, project_name=None, project_version=None, vex=None):  # noqa: E501
        """V1VexBody - a model defined in Swagger"""  # noqa: E501
        self._project = None
        self._project_name = None
        self._project_version = None
        self._vex = None
        self.discriminator = None
        if project is not None:
            self.project = project
        if project_name is not None:
            self.project_name = project_name
        if project_version is not None:
            self.project_version = project_version
        if vex is not None:
            self.vex = vex

    @property
    def project(self):
        """Gets the project of this V1VexBody.  # noqa: E501


        :return: The project of this V1VexBody.  # noqa: E501
        :rtype: str
        """
        return self._project

    @project.setter
    def project(self, project):
        """Sets the project of this V1VexBody.


        :param project: The project of this V1VexBody.  # noqa: E501
        :type: str
        """

        self._project = project

    @property
    def project_name(self):
        """Gets the project_name of this V1VexBody.  # noqa: E501


        :return: The project_name of this V1VexBody.  # noqa: E501
        :rtype: str
        """
        return self._project_name

    @project_name.setter
    def project_name(self, project_name):
        """Sets the project_name of this V1VexBody.


        :param project_name: The project_name of this V1VexBody.  # noqa: E501
        :type: str
        """

        self._project_name = project_name

    @property
    def project_version(self):
        """Gets the project_version of this V1VexBody.  # noqa: E501


        :return: The project_version of this V1VexBody.  # noqa: E501
        :rtype: str
        """
        return self._project_version

    @project_version.setter
    def project_version(self, project_version):
        """Sets the project_version of this V1VexBody.


        :param project_version: The project_version of this V1VexBody.  # noqa: E501
        :type: str
        """

        self._project_version = project_version

    @property
    def vex(self):
        """Gets the vex of this V1VexBody.  # noqa: E501


        :return: The vex of this V1VexBody.  # noqa: E501
        :rtype: str
        """
        return self._vex

    @vex.setter
    def vex(self, vex):
        """Sets the vex of this V1VexBody.


        :param vex: The vex of this V1VexBody.  # noqa: E501
        :type: str
        """

        self._vex = vex

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(V1VexBody, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, V1VexBody):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
