# coding: utf-8

"""
    OWASP Dependency-Track

    REST API of OWASP Dependency-Track  # noqa: E501

    OpenAPI spec version: 4.13.4
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import re  # noqa: F401

# python 2 and python 3 compatibility library
import six

from swagger_client.api_client import ApiClient


class TagApi(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    Ref: https://github.com/swagger-api/swagger-codegen
    """

    def __init__(self, api_client=None):
        if api_client is None:
            api_client = ApiClient()
        self.api_client = api_client

    def create_tags(self, **kwargs):  # noqa: E501
        """Creates one or more tags.  # noqa: E501

        <p>Requires permission <strong>TAG_MANAGEMENT</strong></p>   # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.create_tags(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param list[str] body: Names of the tags to create
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.create_tags_with_http_info(**kwargs)  # noqa: E501
        else:
            (data) = self.create_tags_with_http_info(**kwargs)  # noqa: E501
            return data

    def create_tags_with_http_info(self, **kwargs):  # noqa: E501
        """Creates one or more tags.  # noqa: E501

        <p>Requires permission <strong>TAG_MANAGEMENT</strong></p>   # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.create_tags_with_http_info(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param list[str] body: Names of the tags to create
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['body']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method create_tags" % key
                )
            params[key] = val
        del params['kwargs']

        collection_formats = {}

        path_params = {}

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if 'body' in params:
            body_params = params['body']
        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['ApiKeyAuth', 'BearerAuth']  # noqa: E501

        return self.api_client.call_api(
            '/v1/tag', 'PUT',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def delete_tags(self, **kwargs):  # noqa: E501
        """Deletes one or more tags.  # noqa: E501

        <p>A tag can only be deleted if no projects or policies are assigned to it.</p> <p>   Principals with <strong>PORTFOLIO_MANAGEMENT</strong> permission, and access   to <em>all</em> assigned projects (if portfolio ACL is enabled), can delete   a tag with assigned projects. </p> <p>   Principals with <strong>POLICY_MANAGEMENT</strong> permission can delete tags   with assigned policies. </p> <p>Requires permission <strong>TAG_MANAGEMENT</strong></p>   # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.delete_tags(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param list[str] body: Names of the tags to delete
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.delete_tags_with_http_info(**kwargs)  # noqa: E501
        else:
            (data) = self.delete_tags_with_http_info(**kwargs)  # noqa: E501
            return data

    def delete_tags_with_http_info(self, **kwargs):  # noqa: E501
        """Deletes one or more tags.  # noqa: E501

        <p>A tag can only be deleted if no projects or policies are assigned to it.</p> <p>   Principals with <strong>PORTFOLIO_MANAGEMENT</strong> permission, and access   to <em>all</em> assigned projects (if portfolio ACL is enabled), can delete   a tag with assigned projects. </p> <p>   Principals with <strong>POLICY_MANAGEMENT</strong> permission can delete tags   with assigned policies. </p> <p>Requires permission <strong>TAG_MANAGEMENT</strong></p>   # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.delete_tags_with_http_info(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param list[str] body: Names of the tags to delete
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['body']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method delete_tags" % key
                )
            params[key] = val
        del params['kwargs']

        collection_formats = {}

        path_params = {}

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if 'body' in params:
            body_params = params['body']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/problem+json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['ApiKeyAuth', 'BearerAuth']  # noqa: E501

        return self.api_client.call_api(
            '/v1/tag', 'DELETE',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def get_all_tags(self, **kwargs):  # noqa: E501
        """Returns a list of all tags  # noqa: E501

        <p>Requires permission <strong>VIEW_PORTFOLIO</strong></p>  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_all_tags(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str page_number: The page to return. To be used in conjunction with <code>pageSize</code>.
        :param str page_size: Number of elements to return per page. To be used in conjunction with <code>pageNumber</code>.
        :param str offset: Offset to start returning elements from. To be used in conjunction with <code>limit</code>.
        :param str limit: Number of elements to return per page. To be used in conjunction with <code>offset</code>.
        :param str sort_name: Name of the resource field to sort on.
        :param str sort_order: Ordering of items when sorting with <code>sortName</code>.
        :return: list[TagListResponseItem]
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.get_all_tags_with_http_info(**kwargs)  # noqa: E501
        else:
            (data) = self.get_all_tags_with_http_info(**kwargs)  # noqa: E501
            return data

    def get_all_tags_with_http_info(self, **kwargs):  # noqa: E501
        """Returns a list of all tags  # noqa: E501

        <p>Requires permission <strong>VIEW_PORTFOLIO</strong></p>  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_all_tags_with_http_info(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str page_number: The page to return. To be used in conjunction with <code>pageSize</code>.
        :param str page_size: Number of elements to return per page. To be used in conjunction with <code>pageNumber</code>.
        :param str offset: Offset to start returning elements from. To be used in conjunction with <code>limit</code>.
        :param str limit: Number of elements to return per page. To be used in conjunction with <code>offset</code>.
        :param str sort_name: Name of the resource field to sort on.
        :param str sort_order: Ordering of items when sorting with <code>sortName</code>.
        :return: list[TagListResponseItem]
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['page_number', 'page_size', 'offset', 'limit', 'sort_name', 'sort_order']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method get_all_tags" % key
                )
            params[key] = val
        del params['kwargs']

        collection_formats = {}

        path_params = {}

        query_params = []
        if 'page_number' in params:
            query_params.append(('pageNumber', params['page_number']))  # noqa: E501
        if 'page_size' in params:
            query_params.append(('pageSize', params['page_size']))  # noqa: E501
        if 'offset' in params:
            query_params.append(('offset', params['offset']))  # noqa: E501
        if 'limit' in params:
            query_params.append(('limit', params['limit']))  # noqa: E501
        if 'sort_name' in params:
            query_params.append(('sortName', params['sort_name']))  # noqa: E501
        if 'sort_order' in params:
            query_params.append(('sortOrder', params['sort_order']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['ApiKeyAuth', 'BearerAuth']  # noqa: E501

        return self.api_client.call_api(
            '/v1/tag', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='list[TagListResponseItem]',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def get_tagged_collection_projects(self, name, **kwargs):  # noqa: E501
        """Returns a list of all collection projects that use the given tag for their collection logic.  # noqa: E501

        <p>Requires permission <strong>VIEW_PORTFOLIO</strong></p>  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_tagged_collection_projects(name, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str name: Name of the tag to get collection projects for (required)
        :param str page_number: The page to return. To be used in conjunction with <code>pageSize</code>.
        :param str page_size: Number of elements to return per page. To be used in conjunction with <code>pageNumber</code>.
        :param str offset: Offset to start returning elements from. To be used in conjunction with <code>limit</code>.
        :param str limit: Number of elements to return per page. To be used in conjunction with <code>offset</code>.
        :param str sort_name: Name of the resource field to sort on.
        :param str sort_order: Ordering of items when sorting with <code>sortName</code>.
        :return: list[TaggedCollectionProjectListResponseItem]
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.get_tagged_collection_projects_with_http_info(name, **kwargs)  # noqa: E501
        else:
            (data) = self.get_tagged_collection_projects_with_http_info(name, **kwargs)  # noqa: E501
            return data

    def get_tagged_collection_projects_with_http_info(self, name, **kwargs):  # noqa: E501
        """Returns a list of all collection projects that use the given tag for their collection logic.  # noqa: E501

        <p>Requires permission <strong>VIEW_PORTFOLIO</strong></p>  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_tagged_collection_projects_with_http_info(name, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str name: Name of the tag to get collection projects for (required)
        :param str page_number: The page to return. To be used in conjunction with <code>pageSize</code>.
        :param str page_size: Number of elements to return per page. To be used in conjunction with <code>pageNumber</code>.
        :param str offset: Offset to start returning elements from. To be used in conjunction with <code>limit</code>.
        :param str limit: Number of elements to return per page. To be used in conjunction with <code>offset</code>.
        :param str sort_name: Name of the resource field to sort on.
        :param str sort_order: Ordering of items when sorting with <code>sortName</code>.
        :return: list[TaggedCollectionProjectListResponseItem]
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['name', 'page_number', 'page_size', 'offset', 'limit', 'sort_name', 'sort_order']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method get_tagged_collection_projects" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'name' is set
        if ('name' not in params or
                params['name'] is None):
            raise ValueError("Missing the required parameter `name` when calling `get_tagged_collection_projects`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'name' in params:
            path_params['name'] = params['name']  # noqa: E501

        query_params = []
        if 'page_number' in params:
            query_params.append(('pageNumber', params['page_number']))  # noqa: E501
        if 'page_size' in params:
            query_params.append(('pageSize', params['page_size']))  # noqa: E501
        if 'offset' in params:
            query_params.append(('offset', params['offset']))  # noqa: E501
        if 'limit' in params:
            query_params.append(('limit', params['limit']))  # noqa: E501
        if 'sort_name' in params:
            query_params.append(('sortName', params['sort_name']))  # noqa: E501
        if 'sort_order' in params:
            query_params.append(('sortOrder', params['sort_order']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['ApiKeyAuth', 'BearerAuth']  # noqa: E501

        return self.api_client.call_api(
            '/v1/tag/{name}/collectionProject', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='list[TaggedCollectionProjectListResponseItem]',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def get_tagged_notification_rules(self, name, **kwargs):  # noqa: E501
        """Returns a list of all notification rules assigned to the given tag.  # noqa: E501

        <p>Requires permission <strong>SYSTEM_CONFIGURATION</strong></p>  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_tagged_notification_rules(name, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str name: Name of the tag to get notification rules for (required)
        :param str page_number: The page to return. To be used in conjunction with <code>pageSize</code>.
        :param str page_size: Number of elements to return per page. To be used in conjunction with <code>pageNumber</code>.
        :param str offset: Offset to start returning elements from. To be used in conjunction with <code>limit</code>.
        :param str limit: Number of elements to return per page. To be used in conjunction with <code>offset</code>.
        :param str sort_name: Name of the resource field to sort on.
        :param str sort_order: Ordering of items when sorting with <code>sortName</code>.
        :return: list[TaggedPolicyListResponseItem]
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.get_tagged_notification_rules_with_http_info(name, **kwargs)  # noqa: E501
        else:
            (data) = self.get_tagged_notification_rules_with_http_info(name, **kwargs)  # noqa: E501
            return data

    def get_tagged_notification_rules_with_http_info(self, name, **kwargs):  # noqa: E501
        """Returns a list of all notification rules assigned to the given tag.  # noqa: E501

        <p>Requires permission <strong>SYSTEM_CONFIGURATION</strong></p>  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_tagged_notification_rules_with_http_info(name, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str name: Name of the tag to get notification rules for (required)
        :param str page_number: The page to return. To be used in conjunction with <code>pageSize</code>.
        :param str page_size: Number of elements to return per page. To be used in conjunction with <code>pageNumber</code>.
        :param str offset: Offset to start returning elements from. To be used in conjunction with <code>limit</code>.
        :param str limit: Number of elements to return per page. To be used in conjunction with <code>offset</code>.
        :param str sort_name: Name of the resource field to sort on.
        :param str sort_order: Ordering of items when sorting with <code>sortName</code>.
        :return: list[TaggedPolicyListResponseItem]
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['name', 'page_number', 'page_size', 'offset', 'limit', 'sort_name', 'sort_order']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method get_tagged_notification_rules" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'name' is set
        if ('name' not in params or
                params['name'] is None):
            raise ValueError("Missing the required parameter `name` when calling `get_tagged_notification_rules`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'name' in params:
            path_params['name'] = params['name']  # noqa: E501

        query_params = []
        if 'page_number' in params:
            query_params.append(('pageNumber', params['page_number']))  # noqa: E501
        if 'page_size' in params:
            query_params.append(('pageSize', params['page_size']))  # noqa: E501
        if 'offset' in params:
            query_params.append(('offset', params['offset']))  # noqa: E501
        if 'limit' in params:
            query_params.append(('limit', params['limit']))  # noqa: E501
        if 'sort_name' in params:
            query_params.append(('sortName', params['sort_name']))  # noqa: E501
        if 'sort_order' in params:
            query_params.append(('sortOrder', params['sort_order']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['ApiKeyAuth', 'BearerAuth']  # noqa: E501

        return self.api_client.call_api(
            '/v1/tag/{name}/notificationRule', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='list[TaggedPolicyListResponseItem]',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def get_tagged_policies(self, name, **kwargs):  # noqa: E501
        """Returns a list of all policies assigned to the given tag.  # noqa: E501

        <p>Requires permission <strong>VIEW_PORTFOLIO</strong></p>  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_tagged_policies(name, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str name: Name of the tag to get policies for (required)
        :param str page_number: The page to return. To be used in conjunction with <code>pageSize</code>.
        :param str page_size: Number of elements to return per page. To be used in conjunction with <code>pageNumber</code>.
        :param str offset: Offset to start returning elements from. To be used in conjunction with <code>limit</code>.
        :param str limit: Number of elements to return per page. To be used in conjunction with <code>offset</code>.
        :param str sort_name: Name of the resource field to sort on.
        :param str sort_order: Ordering of items when sorting with <code>sortName</code>.
        :return: list[TaggedPolicyListResponseItem]
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.get_tagged_policies_with_http_info(name, **kwargs)  # noqa: E501
        else:
            (data) = self.get_tagged_policies_with_http_info(name, **kwargs)  # noqa: E501
            return data

    def get_tagged_policies_with_http_info(self, name, **kwargs):  # noqa: E501
        """Returns a list of all policies assigned to the given tag.  # noqa: E501

        <p>Requires permission <strong>VIEW_PORTFOLIO</strong></p>  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_tagged_policies_with_http_info(name, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str name: Name of the tag to get policies for (required)
        :param str page_number: The page to return. To be used in conjunction with <code>pageSize</code>.
        :param str page_size: Number of elements to return per page. To be used in conjunction with <code>pageNumber</code>.
        :param str offset: Offset to start returning elements from. To be used in conjunction with <code>limit</code>.
        :param str limit: Number of elements to return per page. To be used in conjunction with <code>offset</code>.
        :param str sort_name: Name of the resource field to sort on.
        :param str sort_order: Ordering of items when sorting with <code>sortName</code>.
        :return: list[TaggedPolicyListResponseItem]
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['name', 'page_number', 'page_size', 'offset', 'limit', 'sort_name', 'sort_order']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method get_tagged_policies" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'name' is set
        if ('name' not in params or
                params['name'] is None):
            raise ValueError("Missing the required parameter `name` when calling `get_tagged_policies`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'name' in params:
            path_params['name'] = params['name']  # noqa: E501

        query_params = []
        if 'page_number' in params:
            query_params.append(('pageNumber', params['page_number']))  # noqa: E501
        if 'page_size' in params:
            query_params.append(('pageSize', params['page_size']))  # noqa: E501
        if 'offset' in params:
            query_params.append(('offset', params['offset']))  # noqa: E501
        if 'limit' in params:
            query_params.append(('limit', params['limit']))  # noqa: E501
        if 'sort_name' in params:
            query_params.append(('sortName', params['sort_name']))  # noqa: E501
        if 'sort_order' in params:
            query_params.append(('sortOrder', params['sort_order']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['ApiKeyAuth', 'BearerAuth']  # noqa: E501

        return self.api_client.call_api(
            '/v1/tag/{name}/policy', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='list[TaggedPolicyListResponseItem]',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def get_tagged_projects(self, name, **kwargs):  # noqa: E501
        """Returns a list of all projects assigned to the given tag.  # noqa: E501

        <p>Requires permission <strong>VIEW_PORTFOLIO</strong></p>  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_tagged_projects(name, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str name: Name of the tag to get projects for (required)
        :param str page_number: The page to return. To be used in conjunction with <code>pageSize</code>.
        :param str page_size: Number of elements to return per page. To be used in conjunction with <code>pageNumber</code>.
        :param str offset: Offset to start returning elements from. To be used in conjunction with <code>limit</code>.
        :param str limit: Number of elements to return per page. To be used in conjunction with <code>offset</code>.
        :param str sort_name: Name of the resource field to sort on.
        :param str sort_order: Ordering of items when sorting with <code>sortName</code>.
        :return: list[TaggedProjectListResponseItem]
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.get_tagged_projects_with_http_info(name, **kwargs)  # noqa: E501
        else:
            (data) = self.get_tagged_projects_with_http_info(name, **kwargs)  # noqa: E501
            return data

    def get_tagged_projects_with_http_info(self, name, **kwargs):  # noqa: E501
        """Returns a list of all projects assigned to the given tag.  # noqa: E501

        <p>Requires permission <strong>VIEW_PORTFOLIO</strong></p>  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_tagged_projects_with_http_info(name, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str name: Name of the tag to get projects for (required)
        :param str page_number: The page to return. To be used in conjunction with <code>pageSize</code>.
        :param str page_size: Number of elements to return per page. To be used in conjunction with <code>pageNumber</code>.
        :param str offset: Offset to start returning elements from. To be used in conjunction with <code>limit</code>.
        :param str limit: Number of elements to return per page. To be used in conjunction with <code>offset</code>.
        :param str sort_name: Name of the resource field to sort on.
        :param str sort_order: Ordering of items when sorting with <code>sortName</code>.
        :return: list[TaggedProjectListResponseItem]
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['name', 'page_number', 'page_size', 'offset', 'limit', 'sort_name', 'sort_order']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method get_tagged_projects" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'name' is set
        if ('name' not in params or
                params['name'] is None):
            raise ValueError("Missing the required parameter `name` when calling `get_tagged_projects`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'name' in params:
            path_params['name'] = params['name']  # noqa: E501

        query_params = []
        if 'page_number' in params:
            query_params.append(('pageNumber', params['page_number']))  # noqa: E501
        if 'page_size' in params:
            query_params.append(('pageSize', params['page_size']))  # noqa: E501
        if 'offset' in params:
            query_params.append(('offset', params['offset']))  # noqa: E501
        if 'limit' in params:
            query_params.append(('limit', params['limit']))  # noqa: E501
        if 'sort_name' in params:
            query_params.append(('sortName', params['sort_name']))  # noqa: E501
        if 'sort_order' in params:
            query_params.append(('sortOrder', params['sort_order']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['ApiKeyAuth', 'BearerAuth']  # noqa: E501

        return self.api_client.call_api(
            '/v1/tag/{name}/project', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='list[TaggedProjectListResponseItem]',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def get_tags(self, policy_uuid, **kwargs):  # noqa: E501
        """Returns a list of all tags associated with a given policy  # noqa: E501

        <p><strong>Deprecated</strong>. Use <code>/api/v1/tag/policy/{uuid}</code> instead.</p> <p>Requires permission <strong>VIEW_PORTFOLIO</strong></p>   # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_tags(policy_uuid, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str policy_uuid: The UUID of the policy (required)
        :param str page_number: The page to return. To be used in conjunction with <code>pageSize</code>.
        :param str page_size: Number of elements to return per page. To be used in conjunction with <code>pageNumber</code>.
        :param str offset: Offset to start returning elements from. To be used in conjunction with <code>limit</code>.
        :param str limit: Number of elements to return per page. To be used in conjunction with <code>offset</code>.
        :param str sort_name: Name of the resource field to sort on.
        :param str sort_order: Ordering of items when sorting with <code>sortName</code>.
        :return: list[Tag]
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.get_tags_with_http_info(policy_uuid, **kwargs)  # noqa: E501
        else:
            (data) = self.get_tags_with_http_info(policy_uuid, **kwargs)  # noqa: E501
            return data

    def get_tags_with_http_info(self, policy_uuid, **kwargs):  # noqa: E501
        """Returns a list of all tags associated with a given policy  # noqa: E501

        <p><strong>Deprecated</strong>. Use <code>/api/v1/tag/policy/{uuid}</code> instead.</p> <p>Requires permission <strong>VIEW_PORTFOLIO</strong></p>   # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_tags_with_http_info(policy_uuid, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str policy_uuid: The UUID of the policy (required)
        :param str page_number: The page to return. To be used in conjunction with <code>pageSize</code>.
        :param str page_size: Number of elements to return per page. To be used in conjunction with <code>pageNumber</code>.
        :param str offset: Offset to start returning elements from. To be used in conjunction with <code>limit</code>.
        :param str limit: Number of elements to return per page. To be used in conjunction with <code>offset</code>.
        :param str sort_name: Name of the resource field to sort on.
        :param str sort_order: Ordering of items when sorting with <code>sortName</code>.
        :return: list[Tag]
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['policy_uuid', 'page_number', 'page_size', 'offset', 'limit', 'sort_name', 'sort_order']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method get_tags" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'policy_uuid' is set
        if ('policy_uuid' not in params or
                params['policy_uuid'] is None):
            raise ValueError("Missing the required parameter `policy_uuid` when calling `get_tags`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'policy_uuid' in params:
            path_params['policyUuid'] = params['policy_uuid']  # noqa: E501

        query_params = []
        if 'page_number' in params:
            query_params.append(('pageNumber', params['page_number']))  # noqa: E501
        if 'page_size' in params:
            query_params.append(('pageSize', params['page_size']))  # noqa: E501
        if 'offset' in params:
            query_params.append(('offset', params['offset']))  # noqa: E501
        if 'limit' in params:
            query_params.append(('limit', params['limit']))  # noqa: E501
        if 'sort_name' in params:
            query_params.append(('sortName', params['sort_name']))  # noqa: E501
        if 'sort_order' in params:
            query_params.append(('sortOrder', params['sort_order']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['ApiKeyAuth', 'BearerAuth']  # noqa: E501

        return self.api_client.call_api(
            '/v1/tag/{policyUuid}', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='list[Tag]',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def get_tags_for_policy(self, uuid, **kwargs):  # noqa: E501
        """Returns a list of all tags associated with a given policy  # noqa: E501

        <p>Requires permission <strong>VIEW_PORTFOLIO</strong></p>  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_tags_for_policy(uuid, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str uuid: The UUID of the policy (required)
        :param str page_number: The page to return. To be used in conjunction with <code>pageSize</code>.
        :param str page_size: Number of elements to return per page. To be used in conjunction with <code>pageNumber</code>.
        :param str offset: Offset to start returning elements from. To be used in conjunction with <code>limit</code>.
        :param str limit: Number of elements to return per page. To be used in conjunction with <code>offset</code>.
        :param str sort_name: Name of the resource field to sort on.
        :param str sort_order: Ordering of items when sorting with <code>sortName</code>.
        :return: list[Tag]
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.get_tags_for_policy_with_http_info(uuid, **kwargs)  # noqa: E501
        else:
            (data) = self.get_tags_for_policy_with_http_info(uuid, **kwargs)  # noqa: E501
            return data

    def get_tags_for_policy_with_http_info(self, uuid, **kwargs):  # noqa: E501
        """Returns a list of all tags associated with a given policy  # noqa: E501

        <p>Requires permission <strong>VIEW_PORTFOLIO</strong></p>  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_tags_for_policy_with_http_info(uuid, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str uuid: The UUID of the policy (required)
        :param str page_number: The page to return. To be used in conjunction with <code>pageSize</code>.
        :param str page_size: Number of elements to return per page. To be used in conjunction with <code>pageNumber</code>.
        :param str offset: Offset to start returning elements from. To be used in conjunction with <code>limit</code>.
        :param str limit: Number of elements to return per page. To be used in conjunction with <code>offset</code>.
        :param str sort_name: Name of the resource field to sort on.
        :param str sort_order: Ordering of items when sorting with <code>sortName</code>.
        :return: list[Tag]
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['uuid', 'page_number', 'page_size', 'offset', 'limit', 'sort_name', 'sort_order']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method get_tags_for_policy" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'uuid' is set
        if ('uuid' not in params or
                params['uuid'] is None):
            raise ValueError("Missing the required parameter `uuid` when calling `get_tags_for_policy`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'uuid' in params:
            path_params['uuid'] = params['uuid']  # noqa: E501

        query_params = []
        if 'page_number' in params:
            query_params.append(('pageNumber', params['page_number']))  # noqa: E501
        if 'page_size' in params:
            query_params.append(('pageSize', params['page_size']))  # noqa: E501
        if 'offset' in params:
            query_params.append(('offset', params['offset']))  # noqa: E501
        if 'limit' in params:
            query_params.append(('limit', params['limit']))  # noqa: E501
        if 'sort_name' in params:
            query_params.append(('sortName', params['sort_name']))  # noqa: E501
        if 'sort_order' in params:
            query_params.append(('sortOrder', params['sort_order']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['ApiKeyAuth', 'BearerAuth']  # noqa: E501

        return self.api_client.call_api(
            '/v1/tag/policy/{uuid}', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='list[Tag]',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def tag_notification_rules(self, body, name, **kwargs):  # noqa: E501
        """Tags one or more notification rules.  # noqa: E501

        <p>Requires permission <strong>SYSTEM_CONFIGURATION</strong></p>  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.tag_notification_rules(body, name, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param list[str] body: UUIDs of notification rules to tag (required)
        :param str name: Name of the tag to assign (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.tag_notification_rules_with_http_info(body, name, **kwargs)  # noqa: E501
        else:
            (data) = self.tag_notification_rules_with_http_info(body, name, **kwargs)  # noqa: E501
            return data

    def tag_notification_rules_with_http_info(self, body, name, **kwargs):  # noqa: E501
        """Tags one or more notification rules.  # noqa: E501

        <p>Requires permission <strong>SYSTEM_CONFIGURATION</strong></p>  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.tag_notification_rules_with_http_info(body, name, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param list[str] body: UUIDs of notification rules to tag (required)
        :param str name: Name of the tag to assign (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['body', 'name']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method tag_notification_rules" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'body' is set
        if ('body' not in params or
                params['body'] is None):
            raise ValueError("Missing the required parameter `body` when calling `tag_notification_rules`")  # noqa: E501
        # verify the required parameter 'name' is set
        if ('name' not in params or
                params['name'] is None):
            raise ValueError("Missing the required parameter `name` when calling `tag_notification_rules`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'name' in params:
            path_params['name'] = params['name']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if 'body' in params:
            body_params = params['body']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/problem+json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['ApiKeyAuth', 'BearerAuth']  # noqa: E501

        return self.api_client.call_api(
            '/v1/tag/{name}/notificationRule', 'POST',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def tag_policies(self, body, name, **kwargs):  # noqa: E501
        """Tags one or more policies.  # noqa: E501

        <p>Requires permission <strong>POLICY_MANAGEMENT</strong></p>  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.tag_policies(body, name, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param list[str] body: UUIDs of policies to tag (required)
        :param str name: Name of the tag to assign (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.tag_policies_with_http_info(body, name, **kwargs)  # noqa: E501
        else:
            (data) = self.tag_policies_with_http_info(body, name, **kwargs)  # noqa: E501
            return data

    def tag_policies_with_http_info(self, body, name, **kwargs):  # noqa: E501
        """Tags one or more policies.  # noqa: E501

        <p>Requires permission <strong>POLICY_MANAGEMENT</strong></p>  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.tag_policies_with_http_info(body, name, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param list[str] body: UUIDs of policies to tag (required)
        :param str name: Name of the tag to assign (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['body', 'name']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method tag_policies" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'body' is set
        if ('body' not in params or
                params['body'] is None):
            raise ValueError("Missing the required parameter `body` when calling `tag_policies`")  # noqa: E501
        # verify the required parameter 'name' is set
        if ('name' not in params or
                params['name'] is None):
            raise ValueError("Missing the required parameter `name` when calling `tag_policies`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'name' in params:
            path_params['name'] = params['name']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if 'body' in params:
            body_params = params['body']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/problem+json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['ApiKeyAuth', 'BearerAuth']  # noqa: E501

        return self.api_client.call_api(
            '/v1/tag/{name}/policy', 'POST',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def tag_projects(self, body, name, **kwargs):  # noqa: E501
        """Tags one or more projects.  # noqa: E501

        <p>Requires permission <strong>PORTFOLIO_MANAGEMENT</strong></p>  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.tag_projects(body, name, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param list[str] body: UUIDs of projects to tag (required)
        :param str name: Name of the tag to assign (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.tag_projects_with_http_info(body, name, **kwargs)  # noqa: E501
        else:
            (data) = self.tag_projects_with_http_info(body, name, **kwargs)  # noqa: E501
            return data

    def tag_projects_with_http_info(self, body, name, **kwargs):  # noqa: E501
        """Tags one or more projects.  # noqa: E501

        <p>Requires permission <strong>PORTFOLIO_MANAGEMENT</strong></p>  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.tag_projects_with_http_info(body, name, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param list[str] body: UUIDs of projects to tag (required)
        :param str name: Name of the tag to assign (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['body', 'name']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method tag_projects" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'body' is set
        if ('body' not in params or
                params['body'] is None):
            raise ValueError("Missing the required parameter `body` when calling `tag_projects`")  # noqa: E501
        # verify the required parameter 'name' is set
        if ('name' not in params or
                params['name'] is None):
            raise ValueError("Missing the required parameter `name` when calling `tag_projects`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'name' in params:
            path_params['name'] = params['name']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if 'body' in params:
            body_params = params['body']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/problem+json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['ApiKeyAuth', 'BearerAuth']  # noqa: E501

        return self.api_client.call_api(
            '/v1/tag/{name}/project', 'POST',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def untag_notification_rules(self, body, name, **kwargs):  # noqa: E501
        """Untags one or more notification rules.  # noqa: E501

        <p>Requires permission <strong>SYSTEM_CONFIGURATION</strong></p>  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.untag_notification_rules(body, name, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param list[str] body: UUIDs of notification rules to untag (required)
        :param str name: Name of the tag (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.untag_notification_rules_with_http_info(body, name, **kwargs)  # noqa: E501
        else:
            (data) = self.untag_notification_rules_with_http_info(body, name, **kwargs)  # noqa: E501
            return data

    def untag_notification_rules_with_http_info(self, body, name, **kwargs):  # noqa: E501
        """Untags one or more notification rules.  # noqa: E501

        <p>Requires permission <strong>SYSTEM_CONFIGURATION</strong></p>  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.untag_notification_rules_with_http_info(body, name, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param list[str] body: UUIDs of notification rules to untag (required)
        :param str name: Name of the tag (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['body', 'name']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method untag_notification_rules" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'body' is set
        if ('body' not in params or
                params['body'] is None):
            raise ValueError("Missing the required parameter `body` when calling `untag_notification_rules`")  # noqa: E501
        # verify the required parameter 'name' is set
        if ('name' not in params or
                params['name'] is None):
            raise ValueError("Missing the required parameter `name` when calling `untag_notification_rules`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'name' in params:
            path_params['name'] = params['name']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if 'body' in params:
            body_params = params['body']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/problem+json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['ApiKeyAuth', 'BearerAuth']  # noqa: E501

        return self.api_client.call_api(
            '/v1/tag/{name}/notificationRule', 'DELETE',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def untag_policies(self, body, name, **kwargs):  # noqa: E501
        """Untags one or more policies.  # noqa: E501

        <p>Requires permission <strong>POLICY_MANAGEMENT</strong></p>  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.untag_policies(body, name, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param list[str] body: UUIDs of policies to untag (required)
        :param str name: Name of the tag (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.untag_policies_with_http_info(body, name, **kwargs)  # noqa: E501
        else:
            (data) = self.untag_policies_with_http_info(body, name, **kwargs)  # noqa: E501
            return data

    def untag_policies_with_http_info(self, body, name, **kwargs):  # noqa: E501
        """Untags one or more policies.  # noqa: E501

        <p>Requires permission <strong>POLICY_MANAGEMENT</strong></p>  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.untag_policies_with_http_info(body, name, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param list[str] body: UUIDs of policies to untag (required)
        :param str name: Name of the tag (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['body', 'name']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method untag_policies" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'body' is set
        if ('body' not in params or
                params['body'] is None):
            raise ValueError("Missing the required parameter `body` when calling `untag_policies`")  # noqa: E501
        # verify the required parameter 'name' is set
        if ('name' not in params or
                params['name'] is None):
            raise ValueError("Missing the required parameter `name` when calling `untag_policies`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'name' in params:
            path_params['name'] = params['name']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if 'body' in params:
            body_params = params['body']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/problem+json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['ApiKeyAuth', 'BearerAuth']  # noqa: E501

        return self.api_client.call_api(
            '/v1/tag/{name}/policy', 'DELETE',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def untag_projects(self, body, name, **kwargs):  # noqa: E501
        """Untags one or more projects.  # noqa: E501

        <p>Requires permission <strong>PORTFOLIO_MANAGEMENT</strong></p>  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.untag_projects(body, name, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param list[str] body: UUIDs of projects to untag (required)
        :param str name: Name of the tag (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.untag_projects_with_http_info(body, name, **kwargs)  # noqa: E501
        else:
            (data) = self.untag_projects_with_http_info(body, name, **kwargs)  # noqa: E501
            return data

    def untag_projects_with_http_info(self, body, name, **kwargs):  # noqa: E501
        """Untags one or more projects.  # noqa: E501

        <p>Requires permission <strong>PORTFOLIO_MANAGEMENT</strong></p>  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.untag_projects_with_http_info(body, name, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param list[str] body: UUIDs of projects to untag (required)
        :param str name: Name of the tag (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['body', 'name']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method untag_projects" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'body' is set
        if ('body' not in params or
                params['body'] is None):
            raise ValueError("Missing the required parameter `body` when calling `untag_projects`")  # noqa: E501
        # verify the required parameter 'name' is set
        if ('name' not in params or
                params['name'] is None):
            raise ValueError("Missing the required parameter `name` when calling `untag_projects`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'name' in params:
            path_params['name'] = params['name']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if 'body' in params:
            body_params = params['body']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/problem+json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['ApiKeyAuth', 'BearerAuth']  # noqa: E501

        return self.api_client.call_api(
            '/v1/tag/{name}/project', 'DELETE',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)
